#!/bin/sh
export devId=`ifconfig | sed -n '/eth0/p' | sed 's/^.*HWaddr \(.*\):\(.*\):\(.*\):\(.*\):\(.*\):\(.*\)$/\1\2\3\4\5\6/' | awk '{print tolower($0)}'`
export devIp=`ifconfig | sed -n '/eth0/{N;p}' | sed 's/^.*inet addr:\(.*\) B.*$/\1/' | tail -n1`
