#!/bin/sh

case "$1" in
  start)
	echo -n "Starting module IBM Message Router: "
	. /opt/IBM_Message_Router/etc/getdeviceidip
	. /opt/IBM_Message_Router/etc/settings
	/opt/IBM_Message_Router/bin/IBM_MRouterd $devId $devIp $IBM_IBM_MODE $IBM_IBM_ORGID $IBM_IBM_DTYPEID $IBM_IBM_AUTHTOKEN &
	echo "Done"
	exit 0
	;;
  stop)
	echo -n "Stopping module IBM Message Router: "
	killall IBM_MRouterd 2> /dev/null
	echo "Done"
	exit 0
	;;
  restart)
	$0 stop
	$0 start
	;;
  status)
	echo -n "Module IBM Message Router is "
	killall -0 IBM_MRouterd 2> /dev/null
	RETVAL=$?
	if [ $RETVAL = 0 ]; then echo "running"; else echo "stopped"; fi
	exit $RETVAL
	;;
  defaults)
    cp /opt/IBM_Message_Router/etc/defaults /opt/IBM_Message_Router/etc/settings 2> /dev/null
	;;
  *)
	echo "Usage: $0 {start|stop|restart|status|defaults}"
	exit 1
esac
