#!/bin/sh

case "$1" in
  start)
	echo -n "Starting module IBM Message Router: "
	. /opt/IBM_Message_Router/etc/getdeviceidip

	/opt/IBM_Message_Router/bin/IBM_MRouterd $devId $devIp &
	echo "Done"
	exit 0
	;;
  stop)
	echo -n "Stopping module IBM Message Router: "
	killall IBM_MRouterd 2> /dev/null
	echo "Done"
	exit 0
	;;
  restart)
	$0 stop
	$0 start
	;;
  install)
    echo -n "Installing libraries to router: "
    . ./install_libs
	echo "Done"
	exit 0
	;;
  uninstall)
    echo -n "Removing libraries from router: "
	. ./uninstall_libs
	echo "Done"
	exit 0
    ;;
  status)
	echo -n "Module IBM Message Router is "
	killall -0 IBM_MRouterd 2> /dev/null
	RETVAL=$?
	if [ $RETVAL = 0 ]; then echo "running"; else echo "stopped"; fi
	exit $RETVAL
	;;
  *)
	echo "Usage: $0 {start|stop|restart|install|uninstall|status}"
	exit 1
esac
